version: '3'

services:
    redis:
        container_name: redis
        image: redis:latest

    wsgi_app:
        container_name: organize_it
        image: organize_it
        build:
            context: .
        environment:
            DB_HOST: db
            REDIS_HOST: redis
        ports:
            - "8080:8080"
        volumes:
            - ./static_root:/code/static-root
    
    rq:
        container_name: rq
        image: organize_it
        build:
            context: .
        environment:
            DB_HOST: db
            REDIS_HOST: redis
        command: ./manage.py rqworker
        volumes:
            - ./static_root:/code/static-root
    
    db:
        container_name: db
        image: postgres
        restart: always
        volumes:
            - ./postgres_data:/var/lib/postgresql
        environment: 
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=organizeit
            - POSTGRES_DB=organizeit
    
    organize_nginx:
        image: nginx:1.17.4-alpine
        container_name: organize_nginx
        ports:
            - "80:80"
        volumes:
            - ./static_root:/static
            - ./nginx:/etc/nginx/conf.d
