# Generated by Django 3.2 on 2021-05-03 13:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210503_1359'),
        ('calendars', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usergroup'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='calendareventattendee',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
